version: '3.8'

services:
  # Database Service (postgres)
  db:
    image: postgres:latest
    user: postgres
    environment:
      POSTGRES_DB: 'me-conta'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - me-conta-data:/var/lib/postgresql/data
    networks:
      - backend

  # Migration Service
  migration:
    build:
      dockerfile: ./Dockerfile.migration
      target: migration
    depends_on:
      - db
    env_file:
      - .env
      - .env.local
    environment:
      NODE_ENV: docker
      DATABASE_URL: postgres://postgres:@db:5432/me-conta
    networks:
      - backend

  # App backend service
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
      - .env.local
    environment:
      NODE_ENV: docker
      DATABASE_URL: postgres://postgres:@db:5432/me-conta
    networks:
      - backend

volumes:
  me-conta-data:
networks:
  backend:
