FROM node:lts-slim as dependencies
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci

# MIGRATION STAGE
FROM node:lts-slim as migration
WORKDIR /usr/src/app
COPY --from=dependencies /usr/src/app/node_modules ./node_modules
COPY ./ ./
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
CMD ["npm", "run", "typeorm:migration:run"]
