export enum Erros {
  EMAIL_DUPLICADO = 'E-mail duplicado',
  NAO_ENCONTRADO = 'Não encontrado',
  PARAMETROS_INCORRETOS = 'Parâmetros incorretos',
  USUARIO_JA_CADASTRADO = 'Usuário já cadastrado',
  FRENTE_ATUACAO_INEXISTENTE = 'Frente de atuação não existe',
  FRENTE_ATUACAO_INVALIDA = 'Frente de atuação inválida',
  ERRO_AO_ENVIAR_EMAIL = 'Erro ao enviar e-mail',
  SUPERVISOR_NAO_ENCONTRADO = 'Supervisor não encontrado',
  CONFLITO_DE_AGENDA = 'Conflito de agenda',
  VALIDACAO_SENHA = 'deve ser uma senha forte',
  VALIDACAO_TELEFONE = 'deve seguir um dos seguintes formatos: (XX) XXXXX-XXXX, (XX) XXXX-XXXX',
  VALIDACAO_EMAIL = 'E-mail inválido.',
  VALIDACAO_DATA = 'Data deve seguir um dos seguintes formatos: YYYY/mm/dd ou YYYY-mm-dd.',
  IDADE_MINIMA = 'Deve possuir no mínimo 18 anos de idade.',
}
