name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Unit Tests
        run: npm run test:cov
      - name: E2E Tests
        run: | 
          cp .env .env.test
          npm run test:e2e
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      url: https://me-conta-backend.herokuapp.com
    environment: 
      name: DEV
      url: $url
    steps:
      - name: test
        run: echo 'deploy on dev'

  deploy-hml:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: HML
    steps:
      - name: test
        run: echo 'deploy on hml'

  deploy-prd:
    runs-on: ubuntu-latest
    needs: deploy-hml
    environment: PRD
    steps:
      - name: test
        run: echo 'deploy on prd'
