name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Unit Tests
        run: npm run test:cov

  test-e2e-and-sonnar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: E2E Tests
        run: | 
          cp .env .env.test
          npm run test:e2e
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    upload-artifact:
      runs-on: ubuntu-latest
      needs:
      - build-and-test
      - test-e2e-and-sonnar
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: NPM build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: me-conta-backend
          path: dist/

    upload-heroku-container:
      runs-on: ubuntu-latest
      needs:
      - build-and-test
      - test-e2e-and-sonnar
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login no Heroku Container
        working-directory: backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Push Container to Heroku
        working-directory: backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: me-conta-backend
        run: heroku container:push -a $HEROKU_APP_NAME web

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: 
      name: DEV
      url: https://me-conta-backend.herokuapp.com
    steps:
      - name: test
        run: echo 'deploy on dev'

  deploy-hml:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: HML
    steps:
      - name: test
        run: echo 'deploy on hml'

  deploy-prd:
    runs-on: ubuntu-latest
    needs: deploy-hml
    environment: PRD
    steps:
      - name: test
        run: echo 'deploy on prd'
