name: Workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  SHOULD_RUN_SONNARCLOUD: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
      - name: Unit Tests
        run: npm run test:cov
      - name: E2E Tests
        run: | 
          cp .env .env.test
          npm run test:e2e
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: ${{ $SHOULD_RUN_SONNARCLOUD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}